export {default as Loader} from './loader/index'
export {default as Navbar} from './navbar/index'
export {default as Footer} from './footer/index'
export {default as Welcome} from './welcome/index'
export {default as Transactions} from './transactions/index'
export {default as Services} from './services/index'